using System;
using System.Collections.Generic;

namespace HydraX.Library
{
    public partial class BlackOps3
    {
        /// <summary>
        /// Black Ops 3 VehicleSoundDef Logic
        /// </summary>
        private class VehicleSoundDef : IAssetPool
        {
            #region Tables
            /// <summary>
            /// VehicleSoundDef Properties and Struct Offsets
            /// </summary>
            private static readonly Tuple<string, int, int>[] VehicleSoundDefOffsets =
            {
                new Tuple<string, int, int>("simpleEngine",                                                  0x8, 0x6),
                new Tuple<string, int, int>("idleRpms",                                                      0xc, 0x8),
                new Tuple<string, int, int>("maxRpms",                                                       0x10, 0x8),
                new Tuple<string, int, int>("maxTorque",                                                     0x14, 0x8),
                new Tuple<string, int, int>("brakingCoeff",                                                  0x18, 0x8),
                new Tuple<string, int, int>("onLoadFadeInStart",                                             0x1c, 0x8),
                new Tuple<string, int, int>("onLoadFadeInEnd",                                               0x20, 0x8),
                new Tuple<string, int, int>("offLoadFadeOutStart",                                           0x24, 0x8),
                new Tuple<string, int, int>("offLoadFadeOutEnd",                                             0x28, 0x8),
                new Tuple<string, int, int>("onLoadMin",                                                     0x2c, 0x8),
                new Tuple<string, int, int>("onLoadMax",                                                     0x30, 0x8),
                new Tuple<string, int, int>("offLoadMin",                                                    0x34, 0x8),
                new Tuple<string, int, int>("offLoadMax",                                                    0x38, 0x8),
                new Tuple<string, int, int>("loadScale",                                                     0x3c, 0x8),
                new Tuple<string, int, int>("loadSmooting",                                                  0x40, 0x8),
                new Tuple<string, int, int>("throttleLag",                                                   0x44, 0x8),
                new Tuple<string, int, int>("pitchScale",                                                    0x48, 0x8),
                new Tuple<string, int, int>("rpmSmoothing",                                                  0x4c, 0x8),
                new Tuple<string, int, int>("differentialRatio",                                             0x50, 0x8),
                new Tuple<string, int, int>("on_engsnd_name0",                                               0x58, 0x0),
                new Tuple<string, int, int>("on_engsnd_fade_in_start0",                                      0x64, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_in_end0",                                        0x68, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_start0",                                     0x6c, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_end0",                                       0x70, 0x8),
                new Tuple<string, int, int>("on_engsnd_pitch_ref0",                                          0x74, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_min0",                                            0x78, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_max0",                                            0x7c, 0x8),
                new Tuple<string, int, int>("on_engsnd_name1",                                               0x80, 0x0),
                new Tuple<string, int, int>("on_engsnd_fade_in_start1",                                      0x8c, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_in_end1",                                        0x90, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_start1",                                     0x94, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_end1",                                       0x98, 0x8),
                new Tuple<string, int, int>("on_engsnd_pitch_ref1",                                          0x9c, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_min1",                                            0xa0, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_max1",                                            0xa4, 0x8),
                new Tuple<string, int, int>("on_engsnd_name2",                                               0xa8, 0x0),
                new Tuple<string, int, int>("on_engsnd_fade_in_start2",                                      0xb4, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_in_end2",                                        0xb8, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_start2",                                     0xbc, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_end2",                                       0xc0, 0x8),
                new Tuple<string, int, int>("on_engsnd_pitch_ref2",                                          0xc4, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_min2",                                            0xc8, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_max2",                                            0xcc, 0x8),
                new Tuple<string, int, int>("on_engsnd_name3",                                               0xd0, 0x0),
                new Tuple<string, int, int>("on_engsnd_fade_in_start3",                                      0xdc, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_in_end3",                                        0xe0, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_start3",                                     0xe4, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_end3",                                       0xe8, 0x8),
                new Tuple<string, int, int>("on_engsnd_pitch_ref3",                                          0xec, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_min3",                                            0xf0, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_max3",                                            0xf4, 0x8),
                new Tuple<string, int, int>("on_engsnd_name4",                                               0xf8, 0x0),
                new Tuple<string, int, int>("on_engsnd_fade_in_start4",                                      0x104, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_in_end4",                                        0x108, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_start4",                                     0x10c, 0x8),
                new Tuple<string, int, int>("on_engsnd_fade_out_end4",                                       0x110, 0x8),
                new Tuple<string, int, int>("on_engsnd_pitch_ref4",                                          0x114, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_min4",                                            0x118, 0x8),
                new Tuple<string, int, int>("on_engsnd_vol_max4",                                            0x11c, 0x8),
                new Tuple<string, int, int>("off_engsnd_name0",                                              0x120, 0x0),
                new Tuple<string, int, int>("off_engsnd_fade_in_start0",                                     0x12c, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_in_end0",                                       0x130, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_start0",                                    0x134, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_end0",                                      0x138, 0x8),
                new Tuple<string, int, int>("off_engsnd_pitch_ref0",                                         0x13c, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_min0",                                           0x140, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_max0",                                           0x144, 0x8),
                new Tuple<string, int, int>("off_engsnd_name1",                                              0x148, 0x0),
                new Tuple<string, int, int>("off_engsnd_fade_in_start1",                                     0x154, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_in_end1",                                       0x158, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_start1",                                    0x15c, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_end1",                                      0x160, 0x8),
                new Tuple<string, int, int>("off_engsnd_pitch_ref1",                                         0x164, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_min1",                                           0x168, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_max1",                                           0x16c, 0x8),
                new Tuple<string, int, int>("off_engsnd_name2",                                              0x170, 0x0),
                new Tuple<string, int, int>("off_engsnd_fade_in_start2",                                     0x17c, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_in_end2",                                       0x180, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_start2",                                    0x184, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_end2",                                      0x188, 0x8),
                new Tuple<string, int, int>("off_engsnd_pitch_ref2",                                         0x18c, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_min2",                                           0x190, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_max2",                                           0x194, 0x8),
                new Tuple<string, int, int>("off_engsnd_name3",                                              0x198, 0x0),
                new Tuple<string, int, int>("off_engsnd_fade_in_start3",                                     0x1a4, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_in_end3",                                       0x1a8, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_start3",                                    0x1ac, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_end3",                                      0x1b0, 0x8),
                new Tuple<string, int, int>("off_engsnd_pitch_ref3",                                         0x1b4, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_min3",                                           0x1b8, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_max3",                                           0x1bc, 0x8),
                new Tuple<string, int, int>("off_engsnd_name4",                                              0x1c0, 0x0),
                new Tuple<string, int, int>("off_engsnd_fade_in_start4",                                     0x1cc, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_in_end4",                                       0x1d0, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_start4",                                    0x1d4, 0x8),
                new Tuple<string, int, int>("off_engsnd_fade_out_end4",                                      0x1d8, 0x8),
                new Tuple<string, int, int>("off_engsnd_pitch_ref4",                                         0x1dc, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_min4",                                           0x1e0, 0x8),
                new Tuple<string, int, int>("off_engsnd_vol_max4",                                           0x1e4, 0x8),
                new Tuple<string, int, int>("numGears",                                                      0x1e8, 0x4),
                new Tuple<string, int, int>("loopLastGear",                                                  0x1ec, 0x6),
                new Tuple<string, int, int>("gear_min_rpm0",                                                 0x1f0, 0x8),
                new Tuple<string, int, int>("gear_max_rpm0",                                                 0x1f4, 0x8),
                new Tuple<string, int, int>("gear_ratio0",                                                   0x1f8, 0x8),
                new Tuple<string, int, int>("gear_min_rpm1",                                                 0x1fc, 0x8),
                new Tuple<string, int, int>("gear_max_rpm1",                                                 0x200, 0x8),
                new Tuple<string, int, int>("gear_ratio1",                                                   0x204, 0x8),
                new Tuple<string, int, int>("gear_min_rpm2",                                                 0x208, 0x8),
                new Tuple<string, int, int>("gear_max_rpm2",                                                 0x20c, 0x8),
                new Tuple<string, int, int>("gear_ratio2",                                                   0x210, 0x8),
                new Tuple<string, int, int>("gear_min_rpm3",                                                 0x214, 0x8),
                new Tuple<string, int, int>("gear_max_rpm3",                                                 0x218, 0x8),
                new Tuple<string, int, int>("gear_ratio3",                                                   0x21c, 0x8),
                new Tuple<string, int, int>("gear_min_rpm4",                                                 0x220, 0x8),
                new Tuple<string, int, int>("gear_max_rpm4",                                                 0x224, 0x8),
                new Tuple<string, int, int>("gear_ratio4",                                                   0x228, 0x8),
                new Tuple<string, int, int>("gear_min_rpm5",                                                 0x22c, 0x8),
                new Tuple<string, int, int>("gear_max_rpm5",                                                 0x230, 0x8),
                new Tuple<string, int, int>("gear_ratio5",                                                   0x234, 0x8),
                new Tuple<string, int, int>("gear_min_rpm6",                                                 0x238, 0x8),
                new Tuple<string, int, int>("gear_max_rpm6",                                                 0x23c, 0x8),
                new Tuple<string, int, int>("gear_ratio6",                                                   0x240, 0x8),
                new Tuple<string, int, int>("gear_min_rpm7",                                                 0x244, 0x8),
                new Tuple<string, int, int>("gear_max_rpm7",                                                 0x248, 0x8),
                new Tuple<string, int, int>("gear_ratio7",                                                   0x24c, 0x8),
                new Tuple<string, int, int>("gear_min_rpm8",                                                 0x250, 0x8),
                new Tuple<string, int, int>("gear_max_rpm8",                                                 0x254, 0x8),
                new Tuple<string, int, int>("gear_ratio8",                                                   0x258, 0x8),
                new Tuple<string, int, int>("gear_min_rpm9",                                                 0x25c, 0x8),
                new Tuple<string, int, int>("gear_max_rpm9",                                                 0x260, 0x8),
                new Tuple<string, int, int>("gear_ratio9",                                                   0x264, 0x8),
                new Tuple<string, int, int>("use_audio_max_speed",                                           0x268, 0x6),
                new Tuple<string, int, int>("audio_max_speed",                                               0x26c, 0x8),
                new Tuple<string, int, int>("eng_idle_snd_name",                                             0x270, 0x0),
                new Tuple<string, int, int>("eng_idle_start_speed",                                          0x27c, 0x8),
                new Tuple<string, int, int>("eng_idle_end_speed",                                            0x280, 0x8),
                new Tuple<string, int, int>("eng_idle_start_pitch",                                          0x284, 0x8),
                new Tuple<string, int, int>("eng_idle_end_pitch",                                            0x288, 0x8),
                new Tuple<string, int, int>("eng_move_snd_name",                                             0x290, 0x0),
                new Tuple<string, int, int>("eng_move_start_speed",                                          0x29c, 0x8),
                new Tuple<string, int, int>("eng_move_end_speed",                                            0x2a0, 0x8),
                new Tuple<string, int, int>("eng_move_start_pitch",                                          0x2a4, 0x8),
                new Tuple<string, int, int>("eng_move_end_pitch",                                            0x2a8, 0x8),
                new Tuple<string, int, int>("eng_offload_snd_name",                                          0x2b0, 0x0),
                new Tuple<string, int, int>("eng_offload_start_pitch",                                       0x2bc, 0x8),
                new Tuple<string, int, int>("eng_offload_end_pitch",                                         0x2c0, 0x8),
                new Tuple<string, int, int>("engineGraph",                                                   0x2c8, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_radius",                                       0x2d8, 0x8),
                new Tuple<string, int, int>("s_drive_by_sound_radius",                                       0x2dc, 0x8),
                new Tuple<string, int, int>("p_drive_by_sound_apex0",                                        0x2e0, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name0",                                        0x2e8, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex1",                                        0x2f8, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name1",                                        0x300, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex2",                                        0x310, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name2",                                        0x318, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex3",                                        0x328, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name3",                                        0x330, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex4",                                        0x340, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name4",                                        0x348, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex5",                                        0x358, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name5",                                        0x360, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex6",                                        0x370, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name6",                                        0x378, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex7",                                        0x388, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name7",                                        0x390, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex8",                                        0x3a0, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name8",                                        0x3a8, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex9",                                        0x3b8, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name9",                                        0x3c0, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex10",                                       0x3d0, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name10",                                       0x3d8, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex11",                                       0x3e8, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name11",                                       0x3f0, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex12",                                       0x400, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name12",                                       0x408, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex13",                                       0x418, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name13",                                       0x420, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex14",                                       0x430, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name14",                                       0x438, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex15",                                       0x448, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name15",                                       0x450, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex16",                                       0x460, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name16",                                       0x468, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex17",                                       0x478, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name17",                                       0x480, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex18",                                       0x490, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name18",                                       0x498, 0x0),
                new Tuple<string, int, int>("p_drive_by_sound_apex19",                                       0x4a8, 0x4),
                new Tuple<string, int, int>("p_drive_by_sound_name19",                                       0x4b0, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex0",                                        0x4c0, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name0",                                        0x4c8, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex1",                                        0x4d8, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name1",                                        0x4e0, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex2",                                        0x4f0, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name2",                                        0x4f8, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex3",                                        0x508, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name3",                                        0x510, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex4",                                        0x520, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name4",                                        0x528, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex5",                                        0x538, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name5",                                        0x540, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex6",                                        0x550, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name6",                                        0x558, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex7",                                        0x568, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name7",                                        0x570, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex8",                                        0x580, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name8",                                        0x588, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex9",                                        0x598, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name9",                                        0x5a0, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex10",                                       0x5b0, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name10",                                       0x5b8, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex11",                                       0x5c8, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name11",                                       0x5d0, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex12",                                       0x5e0, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name12",                                       0x5e8, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex13",                                       0x5f8, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name13",                                       0x600, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex14",                                       0x610, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name14",                                       0x618, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex15",                                       0x628, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name15",                                       0x630, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex16",                                       0x640, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name16",                                       0x648, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex17",                                       0x658, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name17",                                       0x660, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex18",                                       0x670, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name18",                                       0x678, 0x0),
                new Tuple<string, int, int>("s_drive_by_sound_apex19",                                       0x688, 0x4),
                new Tuple<string, int, int>("s_drive_by_sound_name19",                                       0x690, 0x0),
                new Tuple<string, int, int>("preset_name0",                                                  0x6a0, 0x0),
                new Tuple<string, int, int>("max_speed_vol0",                                                0x6a8, 0x4),
                new Tuple<string, int, int>("min_vol0",                                                      0x6ac, 0x8),
                new Tuple<string, int, int>("max_vol0",                                                      0x6b0, 0x8),
                new Tuple<string, int, int>("max_speed_pitch0",                                              0x6b4, 0x4),
                new Tuple<string, int, int>("min_pitch0",                                                    0x6b8, 0x8),
                new Tuple<string, int, int>("max_pitch0",                                                    0x6bc, 0x8),
                new Tuple<string, int, int>("axis_x0",                                                       0x6c0, 0x6),
                new Tuple<string, int, int>("axis_y0",                                                       0x6c1, 0x6),
                new Tuple<string, int, int>("axis_z0",                                                       0x6c2, 0x6),
                new Tuple<string, int, int>("preset_name1",                                                  0x6c8, 0x0),
                new Tuple<string, int, int>("max_speed_vol1",                                                0x6d0, 0x4),
                new Tuple<string, int, int>("min_vol1",                                                      0x6d4, 0x8),
                new Tuple<string, int, int>("max_vol1",                                                      0x6d8, 0x8),
                new Tuple<string, int, int>("max_speed_pitch1",                                              0x6dc, 0x4),
                new Tuple<string, int, int>("min_pitch1",                                                    0x6e0, 0x8),
                new Tuple<string, int, int>("max_pitch1",                                                    0x6e4, 0x8),
                new Tuple<string, int, int>("axis_x1",                                                       0x6e8, 0x6),
                new Tuple<string, int, int>("axis_y1",                                                       0x6e9, 0x6),
                new Tuple<string, int, int>("axis_z1",                                                       0x6ea, 0x6),
                new Tuple<string, int, int>("preset_name2",                                                  0x6f0, 0x0),
                new Tuple<string, int, int>("max_speed_vol2",                                                0x6f8, 0x4),
                new Tuple<string, int, int>("min_vol2",                                                      0x6fc, 0x8),
                new Tuple<string, int, int>("max_vol2",                                                      0x700, 0x8),
                new Tuple<string, int, int>("max_speed_pitch2",                                              0x704, 0x4),
                new Tuple<string, int, int>("min_pitch2",                                                    0x708, 0x8),
                new Tuple<string, int, int>("max_pitch2",                                                    0x70c, 0x8),
                new Tuple<string, int, int>("axis_x2",                                                       0x710, 0x6),
                new Tuple<string, int, int>("axis_y2",                                                       0x711, 0x6),
                new Tuple<string, int, int>("axis_z2",                                                       0x712, 0x6),
                new Tuple<string, int, int>("preset_name3",                                                  0x718, 0x0),
                new Tuple<string, int, int>("max_speed_vol3",                                                0x720, 0x4),
                new Tuple<string, int, int>("min_vol3",                                                      0x724, 0x8),
                new Tuple<string, int, int>("max_vol3",                                                      0x728, 0x8),
                new Tuple<string, int, int>("max_speed_pitch3",                                              0x72c, 0x4),
                new Tuple<string, int, int>("min_pitch3",                                                    0x730, 0x8),
                new Tuple<string, int, int>("max_pitch3",                                                    0x734, 0x8),
                new Tuple<string, int, int>("axis_x3",                                                       0x738, 0x6),
                new Tuple<string, int, int>("axis_y3",                                                       0x739, 0x6),
                new Tuple<string, int, int>("axis_z3",                                                       0x73a, 0x6),
                new Tuple<string, int, int>("preset_name4",                                                  0x740, 0x0),
                new Tuple<string, int, int>("max_speed_vol4",                                                0x748, 0x4),
                new Tuple<string, int, int>("min_vol4",                                                      0x74c, 0x8),
                new Tuple<string, int, int>("max_vol4",                                                      0x750, 0x8),
                new Tuple<string, int, int>("max_speed_pitch4",                                              0x754, 0x4),
                new Tuple<string, int, int>("min_pitch4",                                                    0x758, 0x8),
                new Tuple<string, int, int>("max_pitch4",                                                    0x75c, 0x8),
                new Tuple<string, int, int>("axis_x4",                                                       0x760, 0x6),
                new Tuple<string, int, int>("axis_y4",                                                       0x761, 0x6),
                new Tuple<string, int, int>("axis_z4",                                                       0x762, 0x6),
                new Tuple<string, int, int>("preset_name5",                                                  0x768, 0x0),
                new Tuple<string, int, int>("max_speed_vol5",                                                0x770, 0x4),
                new Tuple<string, int, int>("min_vol5",                                                      0x774, 0x8),
                new Tuple<string, int, int>("max_vol5",                                                      0x778, 0x8),
                new Tuple<string, int, int>("max_speed_pitch5",                                              0x77c, 0x4),
                new Tuple<string, int, int>("min_pitch5",                                                    0x780, 0x8),
                new Tuple<string, int, int>("max_pitch5",                                                    0x784, 0x8),
                new Tuple<string, int, int>("axis_x5",                                                       0x788, 0x6),
                new Tuple<string, int, int>("axis_y5",                                                       0x789, 0x6),
                new Tuple<string, int, int>("axis_z5",                                                       0x78a, 0x6),
                new Tuple<string, int, int>("preset_name6",                                                  0x790, 0x0),
                new Tuple<string, int, int>("max_speed_vol6",                                                0x798, 0x4),
                new Tuple<string, int, int>("min_vol6",                                                      0x79c, 0x8),
                new Tuple<string, int, int>("max_vol6",                                                      0x7a0, 0x8),
                new Tuple<string, int, int>("max_speed_pitch6",                                              0x7a4, 0x4),
                new Tuple<string, int, int>("min_pitch6",                                                    0x7a8, 0x8),
                new Tuple<string, int, int>("max_pitch6",                                                    0x7ac, 0x8),
                new Tuple<string, int, int>("axis_x6",                                                       0x7b0, 0x6),
                new Tuple<string, int, int>("axis_y6",                                                       0x7b1, 0x6),
                new Tuple<string, int, int>("axis_z6",                                                       0x7b2, 0x6),
                new Tuple<string, int, int>("preset_name7",                                                  0x7b8, 0x0),
                new Tuple<string, int, int>("max_speed_vol7",                                                0x7c0, 0x4),
                new Tuple<string, int, int>("min_vol7",                                                      0x7c4, 0x8),
                new Tuple<string, int, int>("max_vol7",                                                      0x7c8, 0x8),
                new Tuple<string, int, int>("max_speed_pitch7",                                              0x7cc, 0x4),
                new Tuple<string, int, int>("min_pitch7",                                                    0x7d0, 0x8),
                new Tuple<string, int, int>("max_pitch7",                                                    0x7d4, 0x8),
                new Tuple<string, int, int>("axis_x7",                                                       0x7d8, 0x6),
                new Tuple<string, int, int>("axis_y7",                                                       0x7d9, 0x6),
                new Tuple<string, int, int>("axis_z7",                                                       0x7da, 0x6),
                new Tuple<string, int, int>("preset_name8",                                                  0x7e0, 0x0),
                new Tuple<string, int, int>("max_speed_vol8",                                                0x7e8, 0x4),
                new Tuple<string, int, int>("min_vol8",                                                      0x7ec, 0x8),
                new Tuple<string, int, int>("max_vol8",                                                      0x7f0, 0x8),
                new Tuple<string, int, int>("max_speed_pitch8",                                              0x7f4, 0x4),
                new Tuple<string, int, int>("min_pitch8",                                                    0x7f8, 0x8),
                new Tuple<string, int, int>("max_pitch8",                                                    0x7fc, 0x8),
                new Tuple<string, int, int>("axis_x8",                                                       0x800, 0x6),
                new Tuple<string, int, int>("axis_y8",                                                       0x801, 0x6),
                new Tuple<string, int, int>("axis_z8",                                                       0x802, 0x6),
                new Tuple<string, int, int>("preset_name9",                                                  0x808, 0x0),
                new Tuple<string, int, int>("max_speed_vol9",                                                0x810, 0x4),
                new Tuple<string, int, int>("min_vol9",                                                      0x814, 0x8),
                new Tuple<string, int, int>("max_vol9",                                                      0x818, 0x8),
                new Tuple<string, int, int>("max_speed_pitch9",                                              0x81c, 0x4),
                new Tuple<string, int, int>("min_pitch9",                                                    0x820, 0x8),
                new Tuple<string, int, int>("max_pitch9",                                                    0x824, 0x8),
                new Tuple<string, int, int>("axis_x9",                                                       0x828, 0x6),
                new Tuple<string, int, int>("axis_y9",                                                       0x829, 0x6),
                new Tuple<string, int, int>("axis_z9",                                                       0x82a, 0x6),
                new Tuple<string, int, int>("preset_name10",                                                 0x830, 0x0),
                new Tuple<string, int, int>("max_speed_vol10",                                               0x838, 0x4),
                new Tuple<string, int, int>("min_vol10",                                                     0x83c, 0x8),
                new Tuple<string, int, int>("max_vol10",                                                     0x840, 0x8),
                new Tuple<string, int, int>("max_speed_pitch10",                                             0x844, 0x4),
                new Tuple<string, int, int>("min_pitch10",                                                   0x848, 0x8),
                new Tuple<string, int, int>("max_pitch10",                                                   0x84c, 0x8),
                new Tuple<string, int, int>("axis_x10",                                                      0x850, 0x6),
                new Tuple<string, int, int>("axis_y10",                                                      0x851, 0x6),
                new Tuple<string, int, int>("axis_z10",                                                      0x852, 0x6),
                new Tuple<string, int, int>("preset_name11",                                                 0x858, 0x0),
                new Tuple<string, int, int>("max_speed_vol11",                                               0x860, 0x4),
                new Tuple<string, int, int>("min_vol11",                                                     0x864, 0x8),
                new Tuple<string, int, int>("max_vol11",                                                     0x868, 0x8),
                new Tuple<string, int, int>("max_speed_pitch11",                                             0x86c, 0x4),
                new Tuple<string, int, int>("min_pitch11",                                                   0x870, 0x8),
                new Tuple<string, int, int>("max_pitch11",                                                   0x874, 0x8),
                new Tuple<string, int, int>("axis_x11",                                                      0x878, 0x6),
                new Tuple<string, int, int>("axis_y11",                                                      0x879, 0x6),
                new Tuple<string, int, int>("axis_z11",                                                      0x87a, 0x6),
                new Tuple<string, int, int>("preset_name12",                                                 0x880, 0x0),
                new Tuple<string, int, int>("max_speed_vol12",                                               0x888, 0x4),
                new Tuple<string, int, int>("min_vol12",                                                     0x88c, 0x8),
                new Tuple<string, int, int>("max_vol12",                                                     0x890, 0x8),
                new Tuple<string, int, int>("max_speed_pitch12",                                             0x894, 0x4),
                new Tuple<string, int, int>("min_pitch12",                                                   0x898, 0x8),
                new Tuple<string, int, int>("max_pitch12",                                                   0x89c, 0x8),
                new Tuple<string, int, int>("axis_x12",                                                      0x8a0, 0x6),
                new Tuple<string, int, int>("axis_y12",                                                      0x8a1, 0x6),
                new Tuple<string, int, int>("axis_z12",                                                      0x8a2, 0x6),
                new Tuple<string, int, int>("preset_name13",                                                 0x8a8, 0x0),
                new Tuple<string, int, int>("max_speed_vol13",                                               0x8b0, 0x4),
                new Tuple<string, int, int>("min_vol13",                                                     0x8b4, 0x8),
                new Tuple<string, int, int>("max_vol13",                                                     0x8b8, 0x8),
                new Tuple<string, int, int>("max_speed_pitch13",                                             0x8bc, 0x4),
                new Tuple<string, int, int>("min_pitch13",                                                   0x8c0, 0x8),
                new Tuple<string, int, int>("max_pitch13",                                                   0x8c4, 0x8),
                new Tuple<string, int, int>("axis_x13",                                                      0x8c8, 0x6),
                new Tuple<string, int, int>("axis_y13",                                                      0x8c9, 0x6),
                new Tuple<string, int, int>("axis_z13",                                                      0x8ca, 0x6),
                new Tuple<string, int, int>("preset_name14",                                                 0x8d0, 0x0),
                new Tuple<string, int, int>("max_speed_vol14",                                               0x8d8, 0x4),
                new Tuple<string, int, int>("min_vol14",                                                     0x8dc, 0x8),
                new Tuple<string, int, int>("max_vol14",                                                     0x8e0, 0x8),
                new Tuple<string, int, int>("max_speed_pitch14",                                             0x8e4, 0x4),
                new Tuple<string, int, int>("min_pitch14",                                                   0x8e8, 0x8),
                new Tuple<string, int, int>("max_pitch14",                                                   0x8ec, 0x8),
                new Tuple<string, int, int>("axis_x14",                                                      0x8f0, 0x6),
                new Tuple<string, int, int>("axis_y14",                                                      0x8f1, 0x6),
                new Tuple<string, int, int>("axis_z14",                                                      0x8f2, 0x6),
                new Tuple<string, int, int>("preset_name15",                                                 0x8f8, 0x0),
                new Tuple<string, int, int>("max_speed_vol15",                                               0x900, 0x4),
                new Tuple<string, int, int>("min_vol15",                                                     0x904, 0x8),
                new Tuple<string, int, int>("max_vol15",                                                     0x908, 0x8),
                new Tuple<string, int, int>("max_speed_pitch15",                                             0x90c, 0x4),
                new Tuple<string, int, int>("min_pitch15",                                                   0x910, 0x8),
                new Tuple<string, int, int>("max_pitch15",                                                   0x914, 0x8),
                new Tuple<string, int, int>("axis_x15",                                                      0x918, 0x6),
                new Tuple<string, int, int>("axis_y15",                                                      0x919, 0x6),
                new Tuple<string, int, int>("axis_z15",                                                      0x91a, 0x6),
                new Tuple<string, int, int>("preset_name16",                                                 0x920, 0x0),
                new Tuple<string, int, int>("max_speed_vol16",                                               0x928, 0x4),
                new Tuple<string, int, int>("min_vol16",                                                     0x92c, 0x8),
                new Tuple<string, int, int>("max_vol16",                                                     0x930, 0x8),
                new Tuple<string, int, int>("max_speed_pitch16",                                             0x934, 0x4),
                new Tuple<string, int, int>("min_pitch16",                                                   0x938, 0x8),
                new Tuple<string, int, int>("max_pitch16",                                                   0x93c, 0x8),
                new Tuple<string, int, int>("axis_x16",                                                      0x940, 0x6),
                new Tuple<string, int, int>("axis_y16",                                                      0x941, 0x6),
                new Tuple<string, int, int>("axis_z16",                                                      0x942, 0x6),
                new Tuple<string, int, int>("preset_name17",                                                 0x948, 0x0),
                new Tuple<string, int, int>("max_speed_vol17",                                               0x950, 0x4),
                new Tuple<string, int, int>("min_vol17",                                                     0x954, 0x8),
                new Tuple<string, int, int>("max_vol17",                                                     0x958, 0x8),
                new Tuple<string, int, int>("max_speed_pitch17",                                             0x95c, 0x4),
                new Tuple<string, int, int>("min_pitch17",                                                   0x960, 0x8),
                new Tuple<string, int, int>("max_pitch17",                                                   0x964, 0x8),
                new Tuple<string, int, int>("axis_x17",                                                      0x968, 0x6),
                new Tuple<string, int, int>("axis_y17",                                                      0x969, 0x6),
                new Tuple<string, int, int>("axis_z17",                                                      0x96a, 0x6),
                new Tuple<string, int, int>("preset_name18",                                                 0x970, 0x0),
                new Tuple<string, int, int>("max_speed_vol18",                                               0x978, 0x4),
                new Tuple<string, int, int>("min_vol18",                                                     0x97c, 0x8),
                new Tuple<string, int, int>("max_vol18",                                                     0x980, 0x8),
                new Tuple<string, int, int>("max_speed_pitch18",                                             0x984, 0x4),
                new Tuple<string, int, int>("min_pitch18",                                                   0x988, 0x8),
                new Tuple<string, int, int>("max_pitch18",                                                   0x98c, 0x8),
                new Tuple<string, int, int>("axis_x18",                                                      0x990, 0x6),
                new Tuple<string, int, int>("axis_y18",                                                      0x991, 0x6),
                new Tuple<string, int, int>("axis_z18",                                                      0x992, 0x6),
                new Tuple<string, int, int>("preset_name19",                                                 0x998, 0x0),
                new Tuple<string, int, int>("max_speed_vol19",                                               0x9a0, 0x4),
                new Tuple<string, int, int>("min_vol19",                                                     0x9a4, 0x8),
                new Tuple<string, int, int>("max_vol19",                                                     0x9a8, 0x8),
                new Tuple<string, int, int>("max_speed_pitch19",                                             0x9ac, 0x4),
                new Tuple<string, int, int>("min_pitch19",                                                   0x9b0, 0x8),
                new Tuple<string, int, int>("max_pitch19",                                                   0x9b4, 0x8),
                new Tuple<string, int, int>("axis_x19",                                                      0x9b8, 0x6),
                new Tuple<string, int, int>("axis_y19",                                                      0x9b9, 0x6),
                new Tuple<string, int, int>("axis_z19",                                                      0x9ba, 0x6),
                new Tuple<string, int, int>("preset_selected0",                                              0x9c0, 0x0),
                new Tuple<string, int, int>("alias0",                                                        0x9d0, 0x0),
                new Tuple<string, int, int>("tag0",                                                          0x9e0, 0x0),
                new Tuple<string, int, int>("preset_selected1",                                              0x9f0, 0x0),
                new Tuple<string, int, int>("alias1",                                                        0xa00, 0x0),
                new Tuple<string, int, int>("tag1",                                                          0xa10, 0x0),
                new Tuple<string, int, int>("preset_selected2",                                              0xa20, 0x0),
                new Tuple<string, int, int>("alias2",                                                        0xa30, 0x0),
                new Tuple<string, int, int>("tag2",                                                          0xa40, 0x0),
                new Tuple<string, int, int>("preset_selected3",                                              0xa50, 0x0),
                new Tuple<string, int, int>("alias3",                                                        0xa60, 0x0),
                new Tuple<string, int, int>("tag3",                                                          0xa70, 0x0),
                new Tuple<string, int, int>("preset_selected4",                                              0xa80, 0x0),
                new Tuple<string, int, int>("alias4",                                                        0xa90, 0x0),
                new Tuple<string, int, int>("tag4",                                                          0xaa0, 0x0),
                new Tuple<string, int, int>("preset_selected5",                                              0xab0, 0x0),
                new Tuple<string, int, int>("alias5",                                                        0xac0, 0x0),
                new Tuple<string, int, int>("tag5",                                                          0xad0, 0x0),
                new Tuple<string, int, int>("preset_selected6",                                              0xae0, 0x0),
                new Tuple<string, int, int>("alias6",                                                        0xaf0, 0x0),
                new Tuple<string, int, int>("tag6",                                                          0xb00, 0x0),
                new Tuple<string, int, int>("preset_selected7",                                              0xb10, 0x0),
                new Tuple<string, int, int>("alias7",                                                        0xb20, 0x0),
                new Tuple<string, int, int>("tag7",                                                          0xb30, 0x0),
                new Tuple<string, int, int>("preset_selected8",                                              0xb40, 0x0),
                new Tuple<string, int, int>("alias8",                                                        0xb50, 0x0),
                new Tuple<string, int, int>("tag8",                                                          0xb60, 0x0),
                new Tuple<string, int, int>("preset_selected9",                                              0xb70, 0x0),
                new Tuple<string, int, int>("alias9",                                                        0xb80, 0x0),
                new Tuple<string, int, int>("tag9",                                                          0xb90, 0x0),
                new Tuple<string, int, int>("preset_selected10",                                             0xba0, 0x0),
                new Tuple<string, int, int>("alias10",                                                       0xbb0, 0x0),
                new Tuple<string, int, int>("tag10",                                                         0xbc0, 0x0),
                new Tuple<string, int, int>("preset_selected11",                                             0xbd0, 0x0),
                new Tuple<string, int, int>("alias11",                                                       0xbe0, 0x0),
                new Tuple<string, int, int>("tag11",                                                         0xbf0, 0x0),
                new Tuple<string, int, int>("preset_selected12",                                             0xc00, 0x0),
                new Tuple<string, int, int>("alias12",                                                       0xc10, 0x0),
                new Tuple<string, int, int>("tag12",                                                         0xc20, 0x0),
                new Tuple<string, int, int>("preset_selected13",                                             0xc30, 0x0),
                new Tuple<string, int, int>("alias13",                                                       0xc40, 0x0),
                new Tuple<string, int, int>("tag13",                                                         0xc50, 0x0),
                new Tuple<string, int, int>("preset_selected14",                                             0xc60, 0x0),
                new Tuple<string, int, int>("alias14",                                                       0xc70, 0x0),
                new Tuple<string, int, int>("tag14",                                                         0xc80, 0x0),
                new Tuple<string, int, int>("preset_selected15",                                             0xc90, 0x0),
                new Tuple<string, int, int>("alias15",                                                       0xca0, 0x0),
                new Tuple<string, int, int>("tag15",                                                         0xcb0, 0x0),
                new Tuple<string, int, int>("preset_selected16",                                             0xcc0, 0x0),
                new Tuple<string, int, int>("alias16",                                                       0xcd0, 0x0),
                new Tuple<string, int, int>("tag16",                                                         0xce0, 0x0),
                new Tuple<string, int, int>("preset_selected17",                                             0xcf0, 0x0),
                new Tuple<string, int, int>("alias17",                                                       0xd00, 0x0),
                new Tuple<string, int, int>("tag17",                                                         0xd10, 0x0),
                new Tuple<string, int, int>("preset_selected18",                                             0xd20, 0x0),
                new Tuple<string, int, int>("alias18",                                                       0xd30, 0x0),
                new Tuple<string, int, int>("tag18",                                                         0xd40, 0x0),
                new Tuple<string, int, int>("preset_selected19",                                             0xd50, 0x0),
                new Tuple<string, int, int>("alias19",                                                       0xd60, 0x0),
                new Tuple<string, int, int>("tag19",                                                         0xd70, 0x0),
                new Tuple<string, int, int>("surfaceSoundDefault",                                           0xd80, 0x0),
                new Tuple<string, int, int>("surfaceSoundBark",                                              0xd90, 0x0),
                new Tuple<string, int, int>("surfaceSoundBrick",                                             0xda0, 0x0),
                new Tuple<string, int, int>("surfaceSoundCarpet",                                            0xdb0, 0x0),
                new Tuple<string, int, int>("surfaceSoundCloth",                                             0xdc0, 0x0),
                new Tuple<string, int, int>("surfaceSoundConcrete",                                          0xdd0, 0x0),
                new Tuple<string, int, int>("surfaceSoundDirt",                                              0xde0, 0x0),
                new Tuple<string, int, int>("surfaceSoundFlesh",                                             0xdf0, 0x0),
                new Tuple<string, int, int>("surfaceSoundFoliage",                                           0xe00, 0x0),
                new Tuple<string, int, int>("surfaceSoundGlass",                                             0xe10, 0x0),
                new Tuple<string, int, int>("surfaceSoundGrass",                                             0xe20, 0x0),
                new Tuple<string, int, int>("surfaceSoundGravel",                                            0xe30, 0x0),
                new Tuple<string, int, int>("surfaceSoundIce",                                               0xe40, 0x0),
                new Tuple<string, int, int>("surfaceSoundMetal",                                             0xe50, 0x0),
                new Tuple<string, int, int>("surfaceSoundMud",                                               0xe60, 0x0),
                new Tuple<string, int, int>("surfaceSoundPaper",                                             0xe70, 0x0),
                new Tuple<string, int, int>("surfaceSoundPlaster",                                           0xe80, 0x0),
                new Tuple<string, int, int>("surfaceSoundRock",                                              0xe90, 0x0),
                new Tuple<string, int, int>("surfaceSoundSand",                                              0xea0, 0x0),
                new Tuple<string, int, int>("surfaceSoundSnow",                                              0xeb0, 0x0),
                new Tuple<string, int, int>("surfaceSoundWater",                                             0xec0, 0x0),
                new Tuple<string, int, int>("surfaceSoundWood",                                              0xed0, 0x0),
                new Tuple<string, int, int>("surfaceSoundAsphalt",                                           0xee0, 0x0),
                new Tuple<string, int, int>("surfaceSoundCeramic",                                           0xef0, 0x0),
                new Tuple<string, int, int>("surfaceSoundPlastic",                                           0xf00, 0x0),
                new Tuple<string, int, int>("surfaceSoundRubber",                                            0xf10, 0x0),
                new Tuple<string, int, int>("surfaceSoundCushion",                                           0xf20, 0x0),
                new Tuple<string, int, int>("surfaceSoundFruit",                                             0xf30, 0x0),
                new Tuple<string, int, int>("surfaceSoundPaintedMetal",                                      0xf40, 0x0),
                new Tuple<string, int, int>("surfaceSoundMetalThin",                                         0xf80, 0x0),
                new Tuple<string, int, int>("surfaceSoundMetalHollow",                                       0xf90, 0x0),
                new Tuple<string, int, int>("surfaceSoundMetalCatwalk",                                      0xfa0, 0x0),
                new Tuple<string, int, int>("surfaceSoundMetalCar",                                          0xfb0, 0x0),
                new Tuple<string, int, int>("surfaceSoundGlassCar",                                          0xfc0, 0x0),
                new Tuple<string, int, int>("surfaceSoundGlassBulletproof",                                  0xfd0, 0x0),
                new Tuple<string, int, int>("surfaceSoundWaterShallow",                                      0xfe0, 0x0),
                new Tuple<string, int, int>("surfaceSoundBodyArmor",                                         0xff0, 0x0),
            };
            #endregion

            /// <summary>
            /// Size of each asset
            /// </summary>
            public int AssetSize { get; set; }

            /// <summary>
            /// Gets or Sets the number of Assets 
            /// </summary>
            public int AssetCount { get; set; }

            /// <summary>
            /// Gets or Sets the Start Address
            /// </summary>
            public long StartAddress { get; set; }

            /// <summary>
            /// Gets or Sets the End Address
            /// </summary>
            public long EndAddress { get { return StartAddress + (AssetCount * AssetSize); } set => throw new NotImplementedException(); }

            /// <summary>
            /// Gets the Name of this Pool
            /// </summary>
            public string Name => "vehiclesounddef";

            /// <summary>
            /// Gets the Setting Group for this Pool
            /// </summary>
            public string SettingGroup => "Misc";

            /// <summary>
            /// Gets the Index of this Pool
            /// </summary>
            public int Index => (int)AssetPool.vehiclesounddef;

            /// <summary>
            /// Loads Assets from this Asset Pool
            /// </summary>
            public List<Asset> Load(HydraInstance instance)
            {
                var results = new List<Asset>();

                var poolInfo = instance.Reader.ReadStruct<AssetPoolInfo>(instance.Game.AssetPoolsAddress + (Index * 0x20));

                StartAddress = poolInfo.PoolPointer;
                AssetSize = poolInfo.AssetSize;
                AssetCount = poolInfo.PoolSize;

                for(int i = 0; i < AssetCount; i++)
                {
                    var address = StartAddress + (i * AssetSize);
                    var namePointer = instance.Reader.ReadInt64(address);

                    if (IsNullAsset(namePointer))
                        continue;

                    results.Add(new Asset()
                    {
                        Name        = instance.Reader.ReadNullTerminatedString(namePointer),
                        Type        = Name,
                        Zone        = ((BlackOps3)instance.Game).ZoneNames[address],
                        Information = "N/A",
                        Status      = "Loaded",
                        Data        = address,
                        LoadMethod  = ExportAsset,
                    });
                }

                return results;
            }

            /// <summary>
            /// Exports the given asset from this pool
            /// </summary>
            public void ExportAsset(Asset asset, HydraInstance instance)
            {
                var buffer = instance.Reader.ReadBytes((long)asset.Data, AssetSize);

                if (asset.Name != instance.Reader.ReadNullTerminatedString(BitConverter.ToInt64(buffer, 0)))
                    throw new Exception("The asset at the expect memory address has changed. Press the Load Game button to refresh the asset list.");

                var result = ConvertAssetBufferToGDTAsset(buffer, VehicleSoundDefOffsets, instance);

                result.Type = "vehiclesounddef";
                result.Name = asset.Name;
                instance.AddGDTAsset(result, result.Type, result.Name);

                return;
            }

            /// <summary>
            /// Checks if the given asset is a null slot
            /// </summary>
            public bool IsNullAsset(Asset asset)
            {
                return IsNullAsset((long)asset.Data);
            }

            /// <summary>
            /// Checks if the given asset is a null slot
            /// </summary>
            public bool IsNullAsset(long nameAddress)
            {
                return nameAddress >= StartAddress && nameAddress <= EndAddress || nameAddress == 0;
            }
        }
    }
}
